# Generated by Django 3.2.5 on 2021-07-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stream',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
