# Generated by Django 3.2.5 on 2021-07-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_mobile', '0003_stream_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='cover',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
