# Generated by Django 3.2 on 2021-07-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_mobile', '0009_group_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
