# Generated by Django 3.2 on 2021-07-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_mobile', '0010_alter_group_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='price',
            field=models.IntegerField(),
        ),
    ]
